using System.Collections.Generic;

namespace Room7
{

  public class ObjectsDatabase
  {

    public List<ObjectInfo> objects;

    public ObjectsDatabase() {
      objects = new List<ObjectInfo>();
      ObjectInfo obj = new ObjectInfo("aereo");
      obj.color = Colore.Bianco;
      obj.function = Funzione.MezziTrasporto;
      objects.Add(obj);
      obj = new ObjectInfo("alberi");
      obj.numberOfObjects = 3;
      obj.avoidColor(Colore.Verde);
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("anguria");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Verde;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("arancia");
      obj.avoidShape(Forma.Cerchio);
      obj.avoidColor(Colore.Giallo);
      obj.avoidColor(Colore.Arancione);
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("banane");
      obj.numberOfObjects = 2;
      obj.color = Colore.Giallo;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("basket");
      obj.shape = Forma.Cerchio;
      obj.color = Colore.Arancione;
      obj.function = Funzione.Sport;
      objects.Add(obj);
      obj = new ObjectInfo("bersaglio");
      obj.shape = Forma.Cerchio;
      obj.function = Funzione.Sport;
      objects.Add(obj);
      obj = new ObjectInfo("biberon");
      obj.function = Funzione.Bere;
      objects.Add(obj);
      obj = new ObjectInfo("bicchieri");
      obj.numberOfObjects = 4;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("bici");
      obj.avoidColor(Colore.Giallo);
      obj.function = Funzione.MezziTrasporto;
      objects.Add(obj);
      obj = new ObjectInfo("biscotto");
      obj.shape = Forma.Cerchio;
      obj.function = Funzione.Dolci;
      objects.Add(obj);
      obj = new ObjectInfo("borsa");
      obj.color = Colore.Verde;
      obj.function = Funzione.Contenitore;
      objects.Add(obj);
      obj = new ObjectInfo("bottiglia");
      obj.function = Funzione.Bere;
      objects.Add(obj);
      obj = new ObjectInfo("calcio");
      obj.shape = Forma.Cerchio;
      obj.color = Colore.BiancoNero;
      obj.function = Funzione.Sport;
      objects.Add(obj);
      obj = new ObjectInfo("cane");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Marrone;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("cappellino da festa");
      obj.shape = Forma.Cono;
      obj.function = Funzione.Festa;
      objects.Add(obj);
      obj = new ObjectInfo("caramelle");
      obj.numberOfObjects = 4;
      obj.color = Colore.Azzurro;
      obj.function = Funzione.Dolci;
      objects.Add(obj);
      obj = new ObjectInfo("carota");
      obj.avoidShape(Forma.Cono);
      obj.avoidShape(Forma.Triangolo);
      obj.color = Colore.Arancione;
      obj.function = Funzione.Verdura;
      objects.Add(obj);
      obj = new ObjectInfo("castagna");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Marrone;
      objects.Add(obj);
      obj = new ObjectInfo("cerchio");
      obj.shape = Forma.Cerchio;
      obj.color = Colore.Giallo;
      obj.avoidFunction(Funzione.Meteo);
      objects.Add(obj);
      obj = new ObjectInfo("chiave inglese");
      obj.color = Colore.Grigio;
      obj.function = Funzione.Attrezzi;
      objects.Add(obj);
      obj = new ObjectInfo("chiavi");
      obj.numberOfObjects = 4;
      obj.avoidColor(Colore.Grigio);
      obj.avoidFunction(Funzione.Attrezzi);
      objects.Add(obj);
      obj = new ObjectInfo("collare");
      obj.avoidColor(Colore.Rosso);
      obj.function = Funzione.Cane;
      objects.Add(obj);
      obj = new ObjectInfo("coltello");
      obj.color = Colore.Giallo;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("corona");
      obj.color = Colore.Giallo;
      objects.Add(obj);
      obj = new ObjectInfo("cucchiaio");
      obj.color = Colore.Grigio;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("cuccia");
      obj.avoidColor(Colore.Giallo);
      obj.function = Funzione.Cane;
      objects.Add(obj);
      obj = new ObjectInfo("cuore");
      obj.color = Colore.Rosso;
      objects.Add(obj);
      obj = new ObjectInfo("cupcake");
      obj.avoidColor(Colore.Bianco);
      obj.function = Funzione.Dolci;
      objects.Add(obj);
      obj = new ObjectInfo("dado");
      obj.shape = Forma.Cubo;
      obj.color = Colore.BiancoNero;
      objects.Add(obj);
      obj = new ObjectInfo("elicottero");
      obj.avoidColor(Colore.Viola);
      obj.function = Funzione.MezziTrasporto;
      objects.Add(obj);
      obj = new ObjectInfo("fetta anguria");
      obj.shape = Forma.Triangolo;
      obj.color = Colore.Rosso;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("fiore");
      obj.color = Colore.Bianco;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("foglia");
      obj.color = Colore.Verde;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("forbici");
      obj.color = Colore.Viola;
      obj.function = Funzione.Scuola;
      objects.Add(obj);
      obj = new ObjectInfo("forchetta");
      obj.color = Colore.Grigio;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("formaggio");
      obj.shape = Forma.Triangolo;
      obj.color = Colore.Giallo;
      objects.Add(obj);
      obj = new ObjectInfo("formica");
      obj.color = Colore.Nero;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("fungo");
      obj.color = Colore.Rosso;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("gatto");
      obj.color = Colore.BiancoNero;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("gelato");
      obj.shape = Forma.Cono;
      obj.function = Funzione.Dolci;
      objects.Add(obj);
      obj = new ObjectInfo("girasole");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Giallo;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("gonna");
      obj.color = Colore.Rosa;
      obj.function = Funzione.Vestiti;
      objects.Add(obj);
      obj = new ObjectInfo("guinzaglio");
      obj.avoidColor(Colore.Grigio);
      obj.function = Funzione.Cane;
      objects.Add(obj);
      obj = new ObjectInfo("kiwi");
      obj.color = Colore.Verde;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("lampadina");
      obj.color = Colore.Giallo;
      objects.Add(obj);
      obj = new ObjectInfo("lampo");
      obj.color = Colore.Giallo;
      obj.function = Funzione.Meteo;
      objects.Add(obj);
      obj = new ObjectInfo("lente");
      objects.Add(obj);
      obj = new ObjectInfo("libro");
      obj.shape = Forma.Rettangolo;
      obj.color = Colore.Arancione;
      obj.function = Funzione.Scuola;
      objects.Add(obj);
      obj = new ObjectInfo("limone");
      obj.color = Colore.Giallo;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("lollipop");
      obj.function = Funzione.Dolci;
      objects.Add(obj);
      obj = new ObjectInfo("macchina");
      obj.color = Colore.Blu;
      obj.function = Funzione.MezziTrasporto;
      objects.Add(obj);
      obj = new ObjectInfo("maiale");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Rosa;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("martello");
      obj.color = Colore.Marrone;
      obj.function = Funzione.Attrezzi;
      objects.Add(obj);
      obj = new ObjectInfo("matita");
      obj.color = Colore.Rosa;
      obj.function = Funzione.Scuola;
      objects.Add(obj);
      obj = new ObjectInfo("mele");
      obj.numberOfObjects = 3;
      obj.color = Colore.Rosso;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("mondo");
      obj.shape = Forma.Cerchio;
      objects.Add(obj);
      obj = new ObjectInfo("mongolfiere");
      obj.numberOfObjects = 3;
      obj.avoidColor(Colore.Rosso);
      objects.Add(obj);
      obj = new ObjectInfo("motorino");
      obj.color = Colore.Blu;
      obj.function = Funzione.MezziTrasporto;
      objects.Add(obj);
      obj = new ObjectInfo("nido");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Marrone;
      obj.function = Funzione.Nido;
      objects.Add(obj);
      obj = new ObjectInfo("nuvola");
      obj.color = Colore.Grigio;
      obj.function = Funzione.Meteo;
      objects.Add(obj);
      obj = new ObjectInfo("occhiali");
      obj.color = Colore.Bianco;
      objects.Add(obj);
      obj = new ObjectInfo("orologio da polso");
      obj.function = Funzione.MisuraTempo;
      objects.Add(obj);
      obj = new ObjectInfo("orologio da tasca");
      obj.color = Colore.Giallo;
      obj.function = Funzione.MisuraTempo;
      objects.Add(obj);
      obj = new ObjectInfo("padella");
      obj.color = Colore.Nero;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("palloncini");
      obj.numberOfObjects = 3;
      obj.color = Colore.Viola;
      obj.function = Funzione.Festa;
      objects.Add(obj);
      obj = new ObjectInfo("palma");
      obj.color = Colore.Verde;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("penna");
      obj.color = Colore.Blu;
      obj.function = Funzione.Scuola;
      objects.Add(obj);
      obj = new ObjectInfo("pesce");
      obj.color = Colore.Blu;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("pianta");
      objects.Add(obj);
      obj = new ObjectInfo("piatto");
      obj.avoidShape(Forma.Cerchio);
      obj.avoidColor(Colore.Giallo);
      obj.avoidColor(Colore.Arancione);
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("pinze");
      obj.color = Colore.Grigio;
      obj.function = Funzione.Attrezzi;
      objects.Add(obj);
      obj = new ObjectInfo("pioggia");
      obj.color = Colore.Azzurro;
      obj.function = Funzione.Meteo;
      objects.Add(obj);
      obj = new ObjectInfo("piramidi");
      obj.numberOfObjects = 2;
      objects.Add(obj);
      obj = new ObjectInfo("pizza");
      obj.shape = Forma.Triangolo;
      obj.color = Colore.Rosso;
      objects.Add(obj);
      obj = new ObjectInfo("pomodoro");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Rosso;
      obj.function = Funzione.Verdura;
      objects.Add(obj);
      obj = new ObjectInfo("porta");
      obj.shape = Forma.Rettangolo;
      objects.Add(obj);
      obj = new ObjectInfo("pulcino");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Giallo;
      obj.function = Funzione.Animale;
      objects.Add(obj);
      obj = new ObjectInfo("pupazzo neve");
      obj.color = Colore.BiancoNero;
      objects.Add(obj);
      obj = new ObjectInfo("regalo");
      obj.shape = Forma.Cubo;
      obj.color = Colore.Viola;
      obj.function = Funzione.Festa;
      objects.Add(obj);
      obj = new ObjectInfo("smartphone");
      obj.shape = Forma.Rettangolo;
      obj.function = Funzione.Comunicazione;
      objects.Add(obj);
      obj = new ObjectInfo("sole");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Giallo;
      obj.function = Funzione.Meteo;
      objects.Add(obj);
      obj = new ObjectInfo("squadra");
      obj.shape = Forma.Triangolo;
      obj.color = Colore.Azzurro;
      obj.function = Funzione.Scuola;
      objects.Add(obj);
      obj = new ObjectInfo("stella");
      obj.color = Colore.Giallo;
      obj.function = Funzione.Meteo;
      objects.Add(obj);
      obj = new ObjectInfo("tavola");
      obj.avoidColor(Colore.Rosso);
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("tazzina");
      obj.color = Colore.Bianco;
      obj.function = Funzione.Cucina;
      objects.Add(obj);
      obj = new ObjectInfo("telefono");
      obj.color = Colore.Viola;
      obj.function = Funzione.Comunicazione;
      objects.Add(obj);
      obj = new ObjectInfo("tenda");
      obj.shape = Forma.Cono;
      obj.color = Colore.Blu;
      objects.Add(obj);
      obj = new ObjectInfo("trifoglio");
      obj.color = Colore.Verde;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("tronco");
      obj.color = Colore.Marrone;
      obj.function = Funzione.Natura;
      objects.Add(obj);
      obj = new ObjectInfo("tshirt");
      obj.color = Colore.Azzurro;
      obj.function = Funzione.Vestiti;
      objects.Add(obj);
      obj = new ObjectInfo("uovo");
      obj.avoidColor(Colore.Rosa);
      obj.function = Funzione.Nido;
      objects.Add(obj);
      obj = new ObjectInfo("uva");
      obj.color = Colore.Giallo;
      obj.function = Funzione.Frutta;
      objects.Add(obj);
      obj = new ObjectInfo("vaso");
      obj.color = Colore.Azzurro;
      objects.Add(obj);
      obj = new ObjectInfo("volley");
      obj.shape = Forma.Cerchio;
      obj.function = Funzione.Sport;
      objects.Add(obj);
      obj = new ObjectInfo("zaino");
      obj.color = Colore.Rosso;
      obj.function = Funzione.Contenitore;
      objects.Add(obj);
      obj = new ObjectInfo("zucca");
      obj.avoidShape(Forma.Cerchio);
      obj.color = Colore.Arancione;
      obj.function = Funzione.Verdura;
      objects.Add(obj);
    }

  }

}